0xPolygon/kurtosis-pos

src/package_io/input_parser.star
https://github.com/maticnetwork/bor/releases/tag/v1.5.4
=> chore: bump from bor 1.5.3 to 1.5.4

.github/tests/bor-v2-beta.yml
There have been two new bor v2 beta releases the past two weeks:
- [v2.0.0-beta](https://github.com/maticnetwork/bor/releases/tag/v2.0.0-beta)
- [v2.0.0-beta2](https://github.com/maticnetwork/bor/releases/tag/v2.0.0-beta2)
I'd like to see if it can work with the current pos package.
=> ci: test bor v2 beta

.github/tests/all.yml, README.md, src/package_io/input_parser.star
While testing state syncs, there were some issues with `node-20`. It's not ready yet. For now, we'll use `node-16`.
=> chore: revert to `leovct/pos-contract-deployer:node-16`

.github/tests/bor-v2-beta.yml
https://github.com/maticnetwork/bor/releases/tag/v2.0.0
=> chore: bump from `bor:2.0.0-beta2` to `bor:2.0.0`

main.star, src/additional_services/prometheus_grafana.star, src/cl/heimdall/heimdall_launcher.star, src/cl/heimdall_v2/heimdall_v2_launcher.star, src/contracts/contract_deployer.star, src/el/bor/bor_launcher.star, src/el/erigon/erigon_launcher.star, src/el_cl_launcher.star, src/package_io/input_parser.star, src/package_io/sanity_check.star, src/prelaunch_data_generator/cl_genesis/cl_genesis_generator.star, src/prelaunch_data_generator/el_genesis/el_genesis_generator.star
- The new process is to parse arguments first, then add default values, and finally do sanity checks. Before, the order was parse arguments, sanity checks, and then add default values.
- Remove all the defaults values when using `.get()`. The package should fail if a value is missing instead of running with wrong values.
=> fix: sanity check

static_files/heimdall_v2/app.toml, static_files/heimdall_v2/config.toml
Change the default network from mainnet to devnet. Otherwise, some features, such as milestone, won't be enabled at block 0. Also reduce heimdall block time from 5-6s to 1-1.5s.
=> Update heimdall v2 configs

src/el_cl_launcher.star
Wait for L2 startup targets the last CL node instead of the first one...
For reference: https://github.com/0xPolygon/kurtosis-polygon-pos/actions/runs/13522504224/job/37786648024?pr=74#step:6:2293
=> fix: wait for l2 startup should target the first CL node

main.star, src/additional_services/prometheus_grafana.star, src/package_io/constants.star
Kurtosis will always attempt to pull prometheus and grafana packages, even if the `prometheus_grafana` additional service is not specified in the configuration... Our package should only pull package dependencies if needed.
Related issue: https://0xpolygon.slack.com/archives/C048P4UC7SL/p1741184430796209?thread_ts=1741181961.997209&cid=C048P4UC7SL
=> fix: only import package when needed

README.md
The default `params.yml` I used from the readme doesn't have a default EL chain id which leads to this error:
```
Evaluation error: fail: CL chain id must follow the standard "heimdall-<el_chain_id>". Expected "heimdall-" but got: "heimdall-4927".
```
Might be useful to have it in readme for first time users.
=> README: use default el chain id in params.yml

README.md, src/package_io/input_parser.star
New erigon release: https://github.com/erigontech/erigon/releases/tag/v2.61.3
=> feat: bump from erigon `2.61.0` to `2.61.3`

.github/tests/all.yml, .github/tests/contract-deployer-node-16.yml, .github/tests/contract-deployer-node-20.yml, README.md, docker/README.md, docker/pos-contract-deployer-node-16.Dockerfile, docker/pos-contract-deployer-node-20.Dockerfile, docker/pos-el-genesis-builder.Dockerfile, src/contracts/contract_deployer.star, src/package_io/input_parser.star
Our utility images rely on the following repositories:
- https://github.com/maticnetwork/contracts
- https://github.com/0xPolygon/pos-contracts
- https://github.com/maticnetwork/genesis-contracts
Since there have been lots of changes in these repositories, it would be great to:
1) Think how to better label/tag images to make it easier to track which commit/tag it targets.
2) Bump to the latest commits (pos-contracts and genesis-contracts)
https://github.com/0xPolygon/devtools/issues/166
This PR addresses the first point.
- Update docker images to support branch and tag or commit sha - it will be easier to maintain and upgrade.
- Release new images and deprecate old images:
- `leovct/pos-contract-deployer:node-16` => `leovct/pos-contract-deployer-node-16:c4d8e12`
- …
=> chore: update contract deployers and genesis builder images names

README.md, docker/README.md, src/package_io/input_parser.star
- Bump to the latest version of bor modified for heimdall-v2.
- Use a shorter name.
=> chore: bump to `leovct/bor:1a6957c`

main.star, src/additional_services/prometheus_grafana.star, src/contracts/util.star, src/el_cl_launcher.star, src/package_io/constants.star, src/wait/wait.star
- Add more info into the L2 context.
- Fix an issue with L1 and L2 chain ids used in the prometheus grafana additional service.
```bash
$ yq '.networks[0]' $HOME/Downloads/dump_run_with_args_prometheus-grafana_14172485371/files/panoptichain-config/config.yml
{
"name": "L1",
"chain_id": "3151908"
}
```
- Update to the latest version of the grafana package.
- Clean up imports.
- Rename `plan.run_sh` services.
Deployed the package locally and made sure that:
1) prometheus ui works fine and targets are healthy
2) grafana ui works fine and panoptichain dashboard shows metrics
=> fix: prometheus grafana l1 and l2 chain ids

.github/workflows/nightly.yaml
=> ci: remove `nightly` from nightly job names

.github/tests/heimdall-bor.yml, .github/tests/heimdall-erigon.yml, .github/tests/heimdall-v2-bor.yml, .github/tests/nightly/all.yml, .github/tests/nightly/heimdall-bor-minimal.yml, .github/tests/nightly/heimdall-erigon-minimal.yml, .github/tests/nightly/heimdall-v2-bor-minimal.yml, README.md, main.star, src/cl/launcher.star, src/cl/rabbitmq.star, src/el/bor/launcher.star, src/el/erigon/launcher.star, src/el/launcher.star, src/el_cl_launcher.star, src/package_io/constants.star, src/package_io/input_parser.star, src/package_io/sanity_check.star, src/participant.star, static_files/el/bor/config.toml, static_files/el/erigon/config.toml
> **🚨 BREAKING CHANGE 🚨**
We'll soon need to support stateless nodes, and instead of adding complexity with a new `is_stateless` field - in addition to `is_validator`, this PR redefines how participant types are described. It introduces a new field, `kind`, to specify the role of a participant in the network:
- `validator`: Responsible for validating and proposing blocks.
- `rpc`: Provides RPC endpoints for interacting with the network (e.g., querying data, sending transactions).
- `stateless`: A lightweight participant that does not maintain state but serves other purposes (e.g., monitoring or relaying data) - not available yet!
=> refactor: introduce participant kind

.github/tests/nightly/all.yml, README.md, src/config/input_parser.star
- https://github.com/maticnetwork/bor/releases/tag/v2.0.3
- https://github.com/maticnetwork/bor/releases/tag/v2.0.2
=> chore: bump to bor to `2.0.3`

.github/workflows/kurtosis-deploy.yaml, STATELESS.md, src/additional_services/test_runner.star, src/contracts/deployer.star, stateless.yml
- Add documentation for stateless node setup.
- Add CI workflow to test stateless devnet - it builds bor and heimdall-v2 local images on the fly.
- Increase the time taken to deploy L2 because it takes longer than the usual deployment.
=> chore: document stateless testing and add ci test

src/cl/launcher.star, src/el/launcher.star
The nightly deployment job for bor/heimdall-v2 devnets has been experiencing frequent failures due to nodes not starting within the current 10-second timeout window. For reference: https://github.com/0xPolygon/kurtosis-polygon-pos/actions/runs/16108840824/job/45448868090
This change increases the node startup timeout to 60 seconds to accommodate slower initialisation times and improve deployment reliability.
Nightly run with increased timeout: https://github.com/leovct/kurtosis-polygon-pos/actions/runs/16111726157
=> chore: increase node startup timeout

docs/docs/configuration/reference.md, src/config/input_parser.star
- Bump erigon to [3.0.14](https://github.com/erigontech/erigon/releases/tag/v3.0.14)
- Bump bor to [2.2.8](https://github.com/maticnetwork/bor/releases/tag/v2.2.8)
=> chore: bump bor to `2.2.8` and erigon to `3.0.14`

src/additional_services/prometheus_grafana.star
This is the latest panoptichain version that supports both heimdall v1 and v2. Once you remove heimdall v1 from this package, then we can upgrade panoptichain to v4.
=> chore: bump panoptichain version to v3.0.6

static_files/el/genesis/genesis.json
`stateSyncConfirmationDelay` value is used in Bor to delay state syncs by that amount of time. Using a higher value in devnets is causing the state sync test in CI to run for around 3.5 minutes, which is a lot, to be honest. On a testing devnet where we don't care for confirmation delay much and just want to see state sync reach Bor as fast as possible, `32` seems to be a decent value. It gives just the right amount of delay and does not stretch the CI tests. With these config changes, state sync tests in CI would now pass in 1 min and 40 secs, which is a 2-minute reduction of time.
Other configs are ported from the `stateless` branch.
=> chore: use smaller value for stateSyncConfirmationDelay

.github/actions/kurtosis-pre-run/action.yml, .github/scripts/parse_timing.py, .github/scripts/timing-thresholds.txt, .github/workflows/kurtosis-deploy.yaml, .github/workflows/nightly.yaml
- Run `kurtosis run` commands with `--verbosity detailed` to see the duration that each instructions take to execute as well as total instruction execution duration.
- Implement a python script, `.github/scripts/parse_timing.py`, to parse the total execution time and compare it again some thresholds (each environment defines its own thresholds in `.github/scripts/timing-thresholds.txt`).
- Make the CI fail if the package takes more time to deploy than it should.
- Reduce job timeouts (not related).
=> ci: parse kurtosis execution time

static_files/el/bor/config.toml
`bor.logs` is used to index state sync transactions.
=> chore: set bor.logs to true

docs/docs/configuration/reference.md, src/additional_services/launcher.star, src/additional_services/status_checker.star, src/config/constants.star, src/config/input_parser.star, src/config/sanity_check.star
Tested locally:
```bash
$ docker pull ghcr.io/0xpolygon/status-checker:v0.2.8
$ docker tag ghcr.io/0xpolygon/status-checker:v0.2.8 status-checker:v0.2.8
$ cat params.yml
polygon_pos_package:
additional_services:
- status_checker
status_checker_params:
image: status-checker:v0.2.8
$ kurtosis run --enclave test --args-file params.yml .
Starlark code successfully run. No output was returned.
⭐ us on GitHub - https://github.com/kurtosis-tech/kurtosis
INFO[2025-08-27T08:46:27Z] ============================================= 
INFO[2025-08-27T08:46:27Z] ||          Created enclave: test          || 
INFO[2025-08-27T08:46:27Z] ============================================= 
Name:            test
UUID:            6dfb5ae421fc
Status:          RUNNING
Creation Time:   Wed, 27 Aug 2025 08:42:57 UTC …
```
=> feat: allow to customise the status checker image

.github/workflows/nightly.yaml
Nightly jobs have started failing over the past few days because `run-with-cl-el-genesis` now takes slightly longer than 15 minutes, which exceeds the current timeout.
For reference: https://github.com/0xPolygon/kurtosis-pos/actions/runs/17369007315/job/49300864129
=> ci: increase `run-with-cl-el-genesis` job timeout

docs/docs/configuration/reference.md, src/config/constants.star
https://github.com/0xPolygon/bor/releases/tag/v2.2.11
=> chore: bump bor to `v2.2.11`

static_files/additional_services/tx-spammer/loadtest.sh
```
{"info": "PRIVATE_KEY: 0x70ab73de2c3b804c6ac38e54a98bc28e9211c9fb564c83707b3c7e875609b285"}
{"info": "RPC_URL: http://172.16.0.12:8545"}
{"info": "Sending transactions to the rpc"}
Error: unknown flag: --eth-amount
Usage:
polycli loadtest [flags]
polycli loadtest [command]
Available Commands:
uniswapv3   Run Uniswapv3-like load test against an Eth/EVm style JSON-RPC endpoint.
Flags:
--account-funding-amount big.Int         The amount in wei to fund the sending accounts with. Set to 0 to disable account funding (useful for eth-call-only mode or pre-funded accounts).
--adaptive-backoff-factor float          When using adaptive rate limiting, this flag controls our multiplicative decrease value. (default 2)
--adaptive-cycle-duration-seconds uint   When using adaptive rate limiting, this …
```
=> fix: loadtest script

src/config/sanity_check.star
This check was too strict, it was failing when using custom heimdall-v2 builds (e.g. `local/heimdall-v2`)
=> chore: refine validator config generator sanity check

docs/docs/configuration/reference.md, src/config/input_parser.star
We already set `45_000_000` as our goal gas limit on the [miner](https://github.com/0xPolygon/kurtosis-pos/blob/de39cf6168f9220f24edcb5248f9633c8e583663/static_files/el/bor/config.toml#L30). But since the genesis gas limit is currently set to `10_000_000`, it need to slowly progress until reaches the goal target of 45Mi.
Reference:
https://ethereum.org/developers/docs/blocks
> The block gas limit can be adjusted upwards or downwards by a factor of 1/1024 from the previous block's gas limit. As a result, validators can change the block gas limit through consensus.
=> Increase Genesis Gas Limit
